=== Guerino/XML-Parser/src/XML-Samples/Edit_Mensaje.dtd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- Este es el DTD de Edit_Mensaje -->
<!ELEMENT Edit_Mensaje (Mensaje+)>
<!ELEMENT Mensaje (Remitente, Destinatario+, Texto?)>
<!ELEMENT Remitente (Nombre, Mail)>
<!ELEMENT Destinatario (Nombre, Mail+)>
<!ELEMENT Texto (Asunto, Parrafo)>

<!ATTLIST Mensaje prioridad (normal | urgente) normal>
<!ATTLIST Destinatario id ID #REQUIRED>
<!ATTLIST Destinatario sexo (hombre | mujer | dudoso) hombre>
<!ATTLIST Texto idioma CDATA #REQUIRED>

<!ELEMENT Mail (#PCDATA)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Asunto (#PCDATA)>
<!ELEMENT Parrafo (#PCDATA)>

=== Guerino/XML-Parser/src/XML-Samples/Mensaje.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Edit_Mensaje SYSTEM "Edit_Mensaje.dtd">
 <!-- Este comentario 
      no se visualiza 
      en el arbol -->
<Edit_Mensaje>
     <Mensaje prioridad="urgente">
          <Remitente>
               <Nombre>Alfredo Reino</Nombre>
               <Mail>alf@ibium.com</Mail>
          </Remitente>
          <Destinatario id="101" sexo="hombre">
               <Nombre>Bill Clinton</Nombre>
               <Mail>president@whitehouse.gov</Mail>
	       <Mail>president@blackhouse.gov</Mail>
          </Destinatario>
          <!-- Texto del mensaje -->
          <Texto idioma="es">
               <Asunto>Hola Bill</Asunto>
               <Parrafo>
                   Hola que tal? Hace mucho que no escribes. A ver si llamas y quedamos para tomar algo.                   
               </Parrafo>
          </Texto>
     </Mensaje>
</Edit_Mensaje>
